version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - generator
    groups:
      kiota-dependencies:
        patterns:
          - "*kiota*"
      OpenTelemetry:
        patterns:
          - "OpenTelemetry.*"
          - "Azure.Monitor.OpenTelemetry.Exporter"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
